project_id = "qnamtkdqqzchnnynaeli"

[functions.webhook-email]
verify_jwt = false

[functions.webhook-ai-enrichment]
verify_jwt = false

[functions.webhook-products]
verify_jwt = false

[functions.get-products]
verify_jwt = false

[functions.get-intents]
verify_jwt = false

[functions.notify-product-added]
verify_jwt = false

[functions.api-emails]
verify_jwt = false

[functions.api-products]
verify_jwt = false

[functions.api-drafts]
verify_jwt = false

[functions.api-customers]
verify_jwt = false
