project_id = "qnamtkdqqzchnnynaeli"

[functions.webhook-email]
verify_jwt = false

[functions.webhook-ai-enrichment]
verify_jwt = false

[functions.webhook-products]
verify_jwt = false

[functions.get-products]
verify_jwt = false

[functions.get-intents]
verify_jwt = false
