project_id = "qnamtkdqqzchnnynaeli"

[functions.webhook-email]
verify_jwt = false

[functions.webhook-ai-analysis]
verify_jwt = false

[functions.webhook-order-update]
verify_jwt = false

[functions.webhook-products]
verify_jwt = false

[functions.webhook-ai-reply]
verify_jwt = false
